### ISSUE TITLE
Error when trying to run main.py

### ISSUE THREAD

**Issue by Kaustubhk12** [DeepeshAgarawal/Music-Classification-MedleyDB#1]
On running main.py I get the following error:

Traceback (most recent call last):
  File "main.py", line 39, in <module>
    full_test = np.load('fulltest.npy')
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\npyio.py", line 362, in load
    fid = open(file, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'fulltest.npy'

**Comment by saurabhg27** [comment]
fulltest.npy was a numpy array file with all the features used to test the model.
we havent uploaded it.
Also this repo doesnt contain all the files.It just contains the code we wanted to share among the team.

**Comment by DeepeshAgarawal** [comment]
you'll have to use you own data download it from the official website... and then load it...

**Comment by sairameshv** [comment]
Ayyo...I deleted it as it is occupying much storage. Do you have a copy of it??


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Deepesh Agarawal <notifications@github.com> Date: 28/06/2017  22:01  (GMT+05:30) To: DeepeshAgarawal/Music-Classification-MedleyDB <Music-Classification-MedleyDB@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [DeepeshAgarawal/Music-Classification-MedleyDB] Error when trying to run main.py (#1) 
you'll have to use you own data download it from the official website... and then load it...

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/DeepeshAgarawal/Music-Classification-MedleyDB","title":"DeepeshAgarawal/Music-Classification-MedleyDB","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/DeepeshAgarawal/Music-Classification-MedleyDB"}},"updates":{"snippets":[{"icon":"PERSON","message":"@DeepeshAgarawal in #1: you'll have to use you own data download it from the official website... and then load it... \r\n"}],"action":{"name":"View Issue","url":"https://github.com/DeepeshAgarawal/Music-Classification-MedleyDB/issues/1#issuecomment-311715223"}}}
